version: 2.1

release_only: &release_only
  filters:
    tags:
      only: /.*@.*/
    branches:
      ignore: /.*/

staging_only: &staging_only
  filters:
    tags: 
      ignore: /.*/
          
workflows:
  build:
    jobs:
      - install_dependencies
      - build_affected: 
          <<: *staging_only
          requires:
            - install_dependencies
      - build_release:
          <<: *release_only
          requires:
            - install_dependencies

      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       <<: *filters-production # this is calling the previously set yaml anchor

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn set version berry
      - run: yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache

  build_affected:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ./
      - run: yarn set version berry
      - run: yarn run affected:lint
      - run: yarn run affected:build --prod --no-progress --skip-nx-cache
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
      - persist_to_workspace:
          root: ./
          paths:
            - dist/*
  build_release:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ./
      - run: yarn set version berry
      - run: APP=$(echo $CI_COMMIT_TAG | cut -d'@' -f1)
      - run: VERSION=$(echo $CI_COMMIT_TAG | cut -d'@' -f2)
      - run: yarn run nx lint $APP
      - run: yarn run nx build $APP --prod --no-progress --skip-nx-cache
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
      - persist_to_workspace:
          root: ./
          paths:
            - dist/*
