version: 2.1

release_only: &release_only
  filters:
    tags:
      only: /.*@.*/
    branches:
      ignore: /.*/

staging_only: &staging_only
  filters:
    tags: 
      ignore: /.*/
          
parse_tag: &parse_tag
  - run: |
      APP=$(echo $CIRCLE_TAG | cut -d'@' -f1)
      VERSION=$(echo $CIRCLE_TAG | cut -d'@' -f2)

setup_base: &setup_base
  - run: |
      if [ $CIRCLE_BRANCH == "main" ]; then
        BASE=remotes/origin/main~1
      else 
        BASE=remotes/origin/main
      fi

workflows:
  build:
    jobs:
      - install_dependencies
      - build_affected: 
          <<: *staging_only
          requires:
            - install_dependencies
      - build_release:
          <<: *release_only
          requires:
            - install_dependencies

      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       <<: *filters-production # this is calling the previously set yaml anchor

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{.Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run: yarn set version berry
      - run: yarn
      - save_cache:
          key: dependencies-{{.Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  build_affected:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - <<: *setup_base
      - restore_cache:
          key: dependencies-{{.Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ./
      - run: yarn set version berry
      - run: yarn run affected:lint --base=$BASE
      - run: yarn run affected:build --base=$BASE --prod --no-progress --skip-nx-cache
      - save_cache:
          key: dependencies-{{.Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ./
          paths:
            - dist/*

  build_release:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - <<: *parse_tag
      - restore_cache:
          key: dependencies-{{.Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ./
      - run: yarn set version berry
      - run: yarn run nx lint $APP
      - run: yarn run nx build $APP --prod --no-progress --skip-nx-cache
      - save_cache:
          key: dependencies-{{.Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ./
          paths:
            - dist/*
